os: linux
language: generic
sudo: required
dist: trusty
install:
    - curl -sL https://gist.github.com/kylef/5c0475ff02b7c7671d2a/raw/621ef9b29bbb852fdfd2e10ed147b321d792c1e4/swiftenv-install.sh | bash
    - . ~/.swiftenv/init
    - swiftenv install 3.1
script:
    - swift test
